Update build-debug.yml

diff --git a/.github/workflows/build-debug.yml b/.github/workflows/build-debug.yml
--- a/.github/workflows/build-debug.yml
+++ b/.github/workflows/build-debug.yml
@@ -74,13 +74,18 @@ jobs:
 
       - name: Get Config file
         run: |
-          wget ${{ github.event.inputs.configURL }} -O $CONFIG_FILE
-          ver=$(grep 'DESTVER=' $CONFIG_FILE | cut -d = -f 2)
-          if [ -z "$ver" ]; then
-            echo "ERROR: 未在配置文件中找到 DESTVER 字段" >&2
-            exit 1
+          if [ -z "${{ github.event.inputs.configURL }}" ]; then
+            echo "configURL is not defined, using default config file"
+          else
+            wget ${{ github.event.inputs.configURL }} -O $CONFIG_FILE
+            ver=$(grep 'DESTVER=' $CONFIG_FILE | cut -d = -f 2)
+            if [ -z "$ver" ]; then
+              echo "ERROR: 未在配置文件中找到 DESTVER 字段" >&2
+              exit 1
+            fi
+            echo "DESTVER=$ver" >> $GITHUB_ENV          
           fi
-          echo "DESTVER=$ver" >> $GITHUB_ENV
+
 
       - name: Clone source code
         run: |
