mod

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -177,7 +177,13 @@ jobs:
             make -j1 V=s
             status=$?
           fi
-          echo "status=success" >> $GITHUB_OUTPUT
+          if [ $? == 0 ]; then
+            echo "status=success" >> $GITHUB_OUTPUT
+          else
+            echo "Compile failed" >&2
+            exit 1
+          fi
+
           grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
           [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
           echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
